In [2]:
import numpy as np

# Задание 1

In [4]:
x = np.arange(11)
x = x[::-1]
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [3]:
y = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
z1 = np.diag(np.arange(10), k=0)
z1 = z1[::-1]
z1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
b = sum(sum(z1))
b

45

# Задание 3
Решите систему уравнений:
4x + 2y + z = 4;
x + 3y = 12;
5y + 4z = -3;

In [63]:
a1 = np.array( [[4, 3, 1], [1, 3, 0], [0, 5, 4]] )
b1 = ( [4, 12, -3] )

In [64]:
from numpy import linalg

In [65]:
linalg.solve(a1, b1)

array([-0.65853659,  4.2195122 , -6.02439024])

In [66]:
np.allclose( np.dot(a1, linalg.solve(a1, b1)), b1 )

True

# Задание 4

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [21]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [28]:
import matplotlib.pyplot as plt

In [74]:
def cosine( users_stats, next_user_stats ):
    for el in users_stats:
        elLength = np.linalg.norm( el )
        next_user_statsLength = np.linalg.norm( next_user_stats )
        np_dot = np.dot( el, next_user_stats ) / ( elLength * next_user_statsLength )
        if np_dot > 0.9:
            print(el, np_dot)


    
cosine( users_stats, next_user_stats )   

[0 1 1 0 0 0] 0.9486832980505138
